# Generated by Django 5.0.3 on 2024-03-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='cert_code',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
