# Generated by Django 5.0.3 on 2024-05-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulk_Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_file', models.FileField(upload_to='excel_files/')),
            ],
        ),
    ]
