# Generated by Django 5.0.3 on 2024-03-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert_app', '0002_alter_studentdetails_cert_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='department',
            field=models.CharField(choices=[('Comp_Science', 'Computer Science'), ('Mech_Engine', 'Mechanical Engineering'), ('Law', 'Law'), ('Med_Surg', 'Medicine And Surgery')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='grade',
            field=models.CharField(choices=[('First_Class', 'First Class'), ('Second_Class_Upper', 'Second Class Upper'), ('Second_Class_Lower', 'Second Class Lower'), ('Third_Class', 'Third Class')], max_length=20),
        ),
    ]
