# Generated by Django 5.0.3 on 2024-05-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert_app', '0003_alter_studentdetails_cert_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulk_certificate',
            options={'verbose_name': 'Bulk Certificate', 'verbose_name_plural': 'Bulk Certificates'},
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name': 'Certificate', 'verbose_name_plural': 'Certificates'},
        ),
        migrations.AlterModelOptions(
            name='studentdetails',
            options={'verbose_name': 'Student Details', 'verbose_name_plural': 'Student Details'},
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='department',
            field=models.CharField(choices=[('Computer Science', 'Computer Science'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Law', 'Law'), ('Medicine And Surgery', 'Medicine And Surgery')], max_length=50),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='grade',
            field=models.CharField(choices=[('First Class', 'First Class'), ('Second Class Upper', 'Second Class Upper'), ('Second Class Lower', 'Second Class Lower'), ('Third Class', 'Third Class')], max_length=20),
        ),
    ]
