# Generated by Django 5.0.3 on 2024-05-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert_app', '0004_alter_bulk_certificate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='cert_code',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
