# Generated by Django 5.0.3 on 2024-07-31 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert_app', '0005_alter_studentdetails_cert_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='cert_code',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
